from .character_sheet_director import NODE_CLASS_MAPPINGS as _MAIN_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as _MAIN_NAMES
from .sheet_align import NODE_CLASS_MAPPINGS as _ALIGN_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as _ALIGN_NAMES

WEB_DIRECTORY = "./js"

NODE_CLASS_MAPPINGS = {**_MAIN_CLASSES, **_ALIGN_CLASSES}
NODE_DISPLAY_NAME_MAPPINGS = {**_MAIN_NAMES, **_ALIGN_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
